version: "3.9"

services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "8888:8888"
  web:
    image: node:18.17.1
    volumes:
      - ./web:/app
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
